import { Inter, Suwannaphum } from 'next/font/google';
import { useEffect } from 'react';
import './globals.css';

export const inter = Inter({ subsets: ['latin'], variable: '--inter' });
export const suwannaphum = Suwannaphum({
	weight: ['400', '700'],
	subsets: ['khmer'],
	variable: '--suwannaphum',
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html
			lang="en"
			className={
				inter.variable +
				' !cursor-none  lg:[&_*]:!cursor-none ' +
				suwannaphum.variable
			}
		>
			<body className={' min-h-screen bg-dark'}>{children}</body>
		</html>
	);
}
